### ISSUE TITLE
unable to active the plugin in Piwigo 14.4.0

### ISSUE THREAD

**Issue by martiniverydry** [Kipjr/Ldap_Login#154]
Hi,
I've been using this this plugin for very long time. Today I finally updated Piwigo from version 12 to the latest 14.4.0, and unfortunately I am unable to activate the plugin. I am just getting "an error occurred" message. All other plugins are working correctly after the upgrade. I tried also clean Piwigo install, and the issue persist, so it looks like there is some incompatibility between Piwigo 14.4.0 and plugin (13.80.0).
I would appreciate if you could check it.

Marcin

**Comment by martiniverydry** [comment]
I tried again clean install of Piwigo 13, same issue:(

Maybe this log will help:

[Mon May 13 00:38:14.953875 2024] [proxy_fcgi:error] [pid 26063] [client xxxxxxx] AH01071: Got error 'PHP message: [ld_table_exist] > SELECT count(*) as count FROM information_schema.TABLES WHERE (TABLE_SCHEMA = 'piwigo2024') AND (TABLE_NAME = 'piwigo_ldap_login_config')PHP message: [ld
_table_exist] > Try query on databasePHP message: [ld_table_exist] > falsePHP message: PHP Fatal error:  Uncaught Error: Call to undefined function str_starts_with() in /var/www/html/piwigo/plugins/Ldap_Login/class.ldap.php:79\nStack trace:\n#0 /var/www/html/piwigo/plugins/Ldap_Login/class.ldap.php(154): Ldap->write
_log()\n#1 /var/www/html/piwigo/plugins/Ldap_Login/maintain.inc.php(72): Ldap->load_default_config()\n#2 /var/www/html/piwigo/admin/include/plugins.class.php(130): Ldap_Login_maintain->install()\n#3 /var/www/html/piwigo/admin/include/plugins.class.php(170): plugins->perform_action()\n#4 /var/www/html/piwigo/include/
ws_functions/pwg.extensions.php(71): plugins->perform_action()\n#5 /var/www/html/piwigo/include/ws_core.inc.php(600): ws_plugins_performAction()\n#6 /var/www/html/piwigo/include/ws_protocols/rest_handler.php(41): PwgServer->invoke()\n#7 /var/www/html/piwigo/include/ws_core.inc.php(281): PwgRestRequestHandler->handle
Request()\n#8 /var/www/html/piwigo/ws.php(22): PwgServer->run()\n#9 {main}\n  thrown in /var/www/html/piwigo/plugins/Ldap_Login/class.ldap.php on l...'

**Comment by martiniverydry** [comment]
Never mind, I forgot to update the php version in Apache site config
